
title: CoderDojoSannomaru
email: sannomaru@coderdojo.com


baseurl: "/sannomaru" # the subpath of your site, e.g. /blog
url: "https://ituyama.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
layout: default
plugins:
  - jekyll-feed

permalink/:month/:day/:title:output_ext
