
title: CoderDojoSannomaru
email: sannomaru@coderdojo.com


baseurl: "/sannomaru" # the subpath of your site, e.g. /blog
url: "https://ituyama.github.io/sannomaru/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
layout: default
plugins:
  - jekyll-feed

permalink: /:categories/:year/:month/:day/:title:output_ext
