
title: CoderDojoSannomaru
email: sannomaru@coderdojo.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/sannomaru" # the subpath of your site, e.g. /blog
url: "https://ituyama.github.io/sannomaru/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
layout: default
plugins:
  - jekyll-feed
permalink: /:categories/:year/:month/:day/:title:output_ext
