
title: CoderDojoSannomaru
email: sannomaru@coderdojo.com


url: "https://ituyama.github.io/sannomaru" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
layout: default
plugins:
  - jekyll-feed

permalink: /:month/:day/:title:output_ext
gist:
  noscript: false
